---
- block:

  - name: atom | add apt key
    apt_key:
      url: https://packagecloud.io/AtomEditor/atom/gpgkey

  - name: atom | add ppa
    lineinfile:
      path: /etc/apt/sources.list.d/atom.list
      line: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main
      create: true

  - name: atom | install atom
    apt:
      update_cache: true
      name: atom

  become: true
  tags:
  - atom