---
- name: dropbox | Check user
  user: name={{ lookup('env','USER') }} state=present

- name: dropbox | Check user home directory
  stat: path={{ ansible_env.HOME }}
  register: home_present

- debug: msg="dropbox | Path exists and is a directory"
  when: home_present.stat.isdir is defined and home_present.stat.isdir == true

- name: dropbox | Create user directory
  file:
    dest="{{ ansible_env.HOME }}/Dropbox"
    state=directory

- name: dropbox | Create base directory
  file:
    dest: "{{ ansible_env.HOME }}/.dropbox"
    state: directory

- name: dropbox | Add dropbox configuration.
  copy:
    content: '{"personal": {"path": "{{ ansible_env.HOME }}/Dropbox", "host": 12345678 }}'
    dest: "{{ ansible_env.HOME }}/.dropbox/info.json"

- block:
  - name: dropbox | Install Dropbox key
    apt_key:
      keyserver: pgp.mit.edu
      id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

  - name: dropbox | Install Dropbox repository
    apt_repository:
      repo: deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu {{ ansible_distribution_release }} main
      state: present
      filename: dropbox

  - name: dropbox | Install Dropbox
    apt:
      name: dropbox
      state: present

  become: yes
  when: ansible_os_family == 'Debian'

- name: dropbox | Configure KDE to autostart dropboxd
  file: path={{ ansible_env.HOME }}/.config/autostart/dropboxd src={{ ansible_env.HOME }}/.dropbox-dist/dropboxd state=link

- name: dropbox | Check dropboxd status
  command: dropbox status
  register: status

- name: dropbox | Start dropboxd
  shell: dropbox start >/dev/null 2>&1
  when: status.stdout == "Dropbox isn't running!"
