---
- name: i3wm | download and install keyring from sur5r
  apt:
    deb: http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb 
  become: true

- name: i3wm | add ppa from sur5r
  lineinfile:
    path: /etc/apt/sources.list.d/sur5r-i3.list
    line: deb http://debian.sur5r.net/i3/ bionic universe
    create: true
  become: true

- name: i3wm | Install i3wm
  become: true
  apt:
    update_cache: true
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - vim
    - curl
    - i3-wm
    - rofi

- name: i3wm | Ensure i3 config directory
  file:
    dest: '{{ ansible_env.HOME }}/.config/plasma-workspace/env'
    state: directory

- name: i3wm | Use i3 as kde wm
  copy:
    dest: '{{ ansible_env.HOME }}/.config/plasma-workspace/env/wm.sh'
    content: 'export KDEWM=/usr/bin/i3'

- name: i3wm | Use i3 config
  template:
    src: '{{ playbook_dir }}/resources/i3_config.j2'
    dest: '{{ ansible_env.HOME }}/.config/i3/config'
