---
- block:
  - name: insomenia | Add repo key
    apt_key:
      url: https://insomnia.rest/keys/debian-public.key.asc
      state: present

  - name: insomenia | add repo
    apt_repository:
      repo: "deb https://dl.bintray.com/getinsomnia/Insomnia /"
      state: present

  - name: insomenia | Install package
    apt:
      name: "insomnia"
      state: present

  become: true
  tags:
    - insomnia