---

- name: Add insomnia repo key
  become: true
  apt_key:
    url: https://insomnia.rest/keys/debian-public.key.asc
    state: present

- name: add insomnia repo
  become: true
  apt_repository:
    repo: "deb https://dl.bintray.com/getinsomnia/Insomnia /"
    state: present

- name: Install insomnia package
  become: true
  apt:
    name: "insomnia"
    state: present
