---
- block:

  - name: keepass | install addon repo
    apt_repository:
      repo: ppa:dlech/keepass2-plugins
      state: present


  - name: keepass | Install packages
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - keepass2
      - keepass2-plugin-application-indicator
      - xdotool

  become: true
  tags:
    - keepass