---

- name: Install all kinds of packages
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - vim
    - libreoffice
    - gcc
    - build-essential
    - linux-headers-{{ ansible_kernel }}
    - debconf-utils
  tags:
    - generic