---
- block:

  - name: wireshark | add repo
    apt_repository:
      repo: ppa:wireshark-dev/stable

  - name: wireshark | Install wireshark
    apt:
      name: "wireshark"
      state: present

  - name: wireshark | allow non-root users to capture
    debconf:
      name: wireshark-common
      question: wireshark-common/install-setuid
      vtype: boolean
      value: 'true'

  - name: wireshark | adding user '{{ ansible_user_id }}' to group sudo
    user:
      name: '{{ ansible_user_id }}'
      groups: wireshark
      append: yes


  become: true
  tags:
    - wireshark